# Site settings
title: Amn's Blog
description: Modern day ramblings
keywords: Aman, Aman Satija, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
