# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
#baseurl: /sustain/
baseurl: /
title: Aman Satija
author: Aman Satija
description: Personal blog and resume
avatar: profile.png
email: satija.aman@gmail.com
github: amansatija/sustain # username
twitter: amansatija
linkedin: amansatija
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
